version: '3.0'

expectations:
  population_size: 3000

actions:
  extract_population:
    run: databuilder:v0.69.0 generate-dataset "analysis/dataset_definition.py" --dummy-tables "dummy-tables/" --output "output/isaric_raw_population.csv.gz"
    outputs:
      highly_sensitive:
        population: output/isaric_raw_population.csv.gz
