################################################################################
#
# Description: This script defines the project pipeline - it specifys the
#              execution orders for all the code in this repo using a series of
#              actions.
#
# Author(s): M Green
# Date last updated: 07/08/2023
#
################################################################################

version: '3.0'

expectations:
  population_size: 1000

actions:

  # Extract isaric data (ehrQL) ----
  extract_first_isaric_admission:
    run: >
      ehrql:v0 generate-dataset analysis/dataset_definition_isaric.py
      --output 'output/admissions/isaric_admission1.csv.gz'
    outputs:
      highly_sensitive:
        csv: output/admissions/isaric_admission1.csv.gz


  # Extract sus data (ehrQL)----
  extract_first_sus_admission_methodA_ehrQL:
    run: >
      ehrql:v0
        generate-dataset analysis/dataset_definition_sus.py
        --output output/admissions/sus_methodA_admission1_ehrQL.csv.gz
        --
        --admission_method A
    outputs:
      highly_sensitive:
        cohort: output/admissions/sus_methodA_admission1_ehrQL.csv.gz

  extract_first_sus_admission_methodB_ehrQL:
    run: >
      ehrql:v0
        generate-dataset analysis/dataset_definition_sus.py
        --output output/admissions/sus_methodB_admission1_ehrQL.csv.gz
        --
        --admission_method B
    outputs:
      highly_sensitive:
        cohort: output/admissions/sus_methodB_admission1_ehrQL.csv.gz

  extract_first_sus_admission_methodC_ehrQL:
    run: >
      ehrql:v0
        generate-dataset analysis/dataset_definition_sus.py
        --output output/admissions/sus_methodC_admission1_ehrQL.csv.gz
        --
        --admission_method C
    outputs:
      highly_sensitive:
        cohort: output/admissions/sus_methodC_admission1_ehrQL.csv.gz


  # Extract sus data (cohortextractor)----
  extract_sus_methodA_admission1_cohortextractor:
    run: >
      cohortextractor:latest generate_cohort
      --study-definition study_definition_sus
      --output-file output/admissions/sus_methodA_admission1_cohortextractor.csv.gz
      --param admission_number=1
      --param admission_method=A
    outputs:
      highly_sensitive:
        csv: output/admissions/sus_methodA_admission1_cohortextractor.csv.gz

  extract_sus_methodB_admission1_cohortextractor:
    run: >
      cohortextractor:latest generate_cohort
      --study-definition study_definition_sus
      --output-file output/admissions/sus_methodB_admission1_cohortextractor.csv.gz
      --param admission_number=1
      --param admission_method=B
    outputs:
      highly_sensitive:
        csv: output/admissions/sus_methodB_admission1_cohortextractor.csv.gz

  extract_sus_methodC_admission1_cohortextractor:
    run: >
      cohortextractor:latest generate_cohort
      --study-definition study_definition_sus
      --output-file output/admissions/sus_methodC_admission1_cohortextractor.csv.gz
      --param admission_number=1
      --param admission_method=C
    outputs:
      highly_sensitive:
        csv: output/admissions/sus_methodC_admission1_cohortextractor.csv.gz

  # Data properties ----
  data_properties:
    run: >
      r:latest
        analysis/data_properties.R
        output/admissions/isaric_admission1.csv.gz
        output/admissions/sus_methodA_admission1_cohortextractor.csv.gz
        output/admissions/sus_methodA_admission1_ehrQL.csv.gz
        output/data_properties
    needs: [extract_first_isaric_admission, extract_sus_methodA_admission1_cohortextractor, extract_first_sus_admission_methodA_ehrQL]
    outputs:
      moderately_sensitive:
        txt1: output/data_properties/*.txt


  # ehrQL vs cohortextractor ----

